#!/bin/bash
# entrypoint.sh — Generate .gh-api-examples.conf from environment variables,
# then exec the user's command (typically perf-test-runner.py).
#
# Required environment variables:
#   GHES_HOST       — GHES hostname or IP (e.g. 192.168.2.251)
#   GHES_TOKEN      — Personal access token
#
# Optional:
#   GHES_ORG        — Organization name   (default: load-test-org)
#   GHES_REPO       — Repository name     (default: loadtest-repo)
#   GHES_ADMIN_USER — Admin username       (default: ghe-admin)

set -euo pipefail

: "${GHES_HOST:?GHES_HOST environment variable is required}"
: "${GHES_TOKEN:?GHES_TOKEN environment variable is required}"

GHES_ORG="${GHES_ORG:-load-test-org}"
GHES_REPO="${GHES_REPO:-loadtest-repo}"
GHES_ADMIN_USER="${GHES_ADMIN_USER:-ghe-admin}"

# Generate the config file that all project scripts source.
# Written to /app/.gh-api-examples.conf (WORKDIR) — overwrites the local-dev shim.
cat > /app/.gh-api-examples.conf <<EOF
# Auto-generated by entrypoint.sh — do not edit manually
hostname=${GHES_HOST}
path_prefix=/api/v3
graphql_path_prefix=/api/graphql
GITHUB_API_BASE_URL=https://${GHES_HOST}/api/v3
GITHUB_APIV4_BASE_URL=https://${GHES_HOST}/api/graphql

token=${GHES_TOKEN}
GITHUB_TOKEN=${GHES_TOKEN}
auth_header="Authorization: token ${GHES_TOKEN}"

U=${GHES_ADMIN_USER}
admin_user=${GHES_ADMIN_USER}
org="${GHES_ORG}"
owner="${GHES_ORG}"
repo="${GHES_REPO}"

default_issue_id=1
default_pull_request_id=2
base_branch=main
branch_name="new_branch"
per_page=30
github_api_version=2022-11-28
curl_custom_flags="--no-progress-meter --fail-with-body -k"
team="Justice League"
team_slug="justice-league"
team_id=
team_members="mona hubot mario luigi"
team_permission="push"
EOF

echo "  Config generated for ${GHES_HOST} (org=${GHES_ORG}, repo=${GHES_REPO})"

exec "$@"
